// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Solution_Magasin.Models;

#nullable disable

namespace Solution_Magasin.Migrations.DotnetProject
{
    [DbContext(typeof(DotnetProjectContext))]
    partial class DotnetProjectContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Solution_Magasin.Models.Achat", b =>
                {
                    b.Property<int>("IdAchat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_achat");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAchat"));

                    b.Property<DateTime?>("DateAchat")
                        .HasColumnType("datetime")
                        .HasColumnName("date_achat");

                    b.Property<int>("IdFourni")
                        .HasColumnType("int")
                        .HasColumnName("id_fourni");

                    b.Property<double?>("TotalAch")
                        .HasColumnType("float")
                        .HasColumnName("total_ach");

                    b.HasKey("IdAchat")
                        .HasName("PK__Achat__ED270182E8DFCDB2");

                    b.HasIndex("IdFourni");

                    b.ToTable("Achat");
                });

            modelBuilder.Entity("Solution_Magasin.Models.Article", b =>
                {
                    b.Property<int>("IdArticle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_article");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdArticle"));

                    b.Property<DateOnly?>("DateAjout")
                        .HasColumnType("date")
                        .HasColumnName("date_ajout");

                    b.Property<string>("DesignationArt")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("designation_art");

                    b.Property<int?>("IdCat")
                        .HasColumnType("int")
                        .HasColumnName("id_cat");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("image_path");

                    b.Property<string>("NomArt")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nom_art");

                    b.Property<double?>("PrixUnit")
                        .HasColumnType("float")
                        .HasColumnName("prix_unit");

                    b.Property<string>("ReferenceArt")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("reference_art");

                    b.HasKey("IdArticle")
                        .HasName("PK__Article__64CB31B8FDBA7DD5");

                    b.HasIndex("IdCat");

                    b.ToTable("Article");
                });

            modelBuilder.Entity("Solution_Magasin.Models.Categorie", b =>
                {
                    b.Property<int>("IdCat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_cat");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCat"));

                    b.Property<string>("DescriptionCat")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("description_cat");

                    b.Property<string>("NomCat")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nom_cat");

                    b.HasKey("IdCat")
                        .HasName("PK__Categori__D54686DEFF867280");

                    b.ToTable("Categorie");
                });

            modelBuilder.Entity("Solution_Magasin.Models.Client", b =>
                {
                    b.Property<int>("IdClient")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_client");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdClient"));

                    b.Property<string>("AdresseClient")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("adresse_client");

                    b.Property<string>("MailClient")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("mail_client");

                    b.Property<string>("NomClient")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nom_client");

                    b.Property<string>("PrenomClient")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("prenom_client");

                    b.Property<string>("TelClient")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("tel_client");

                    b.HasKey("IdClient")
                        .HasName("PK__Client__6EC2B6C07F78BFA5");

                    b.ToTable("Client");
                });

            modelBuilder.Entity("Solution_Magasin.Models.DetailAchat", b =>
                {
                    b.Property<int>("IdDa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_da");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDa"));

                    b.Property<int>("IdAchat")
                        .HasColumnType("int")
                        .HasColumnName("id_achat");

                    b.Property<int>("IdArticle")
                        .HasColumnType("int")
                        .HasColumnName("id_article");

                    b.Property<double?>("MontantDa")
                        .HasColumnType("float")
                        .HasColumnName("montant_da");

                    b.Property<int?>("QteDa")
                        .HasColumnType("int")
                        .HasColumnName("qte_da");

                    b.HasKey("IdDa")
                        .HasName("PK__DetailAc__00B7C6E67393A75E");

                    b.HasIndex("IdAchat");

                    b.HasIndex("IdArticle");

                    b.ToTable("DetailAchat");
                });

            modelBuilder.Entity("Solution_Magasin.Models.DetailVente", b =>
                {
                    b.Property<int>("IdDv")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_dv");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDv"));

                    b.Property<int>("IdArticle")
                        .HasColumnType("int")
                        .HasColumnName("id_article");

                    b.Property<int>("IdVente")
                        .HasColumnType("int")
                        .HasColumnName("id_vente");

                    b.Property<double?>("MontantDv")
                        .HasColumnType("float")
                        .HasColumnName("montant_dv");

                    b.Property<int?>("QteDv")
                        .HasColumnType("int")
                        .HasColumnName("qte_dv");

                    b.HasKey("IdDv")
                        .HasName("PK__DetailVe__00B7C6CD84831A7A");

                    b.HasIndex("IdArticle");

                    b.HasIndex("IdVente");

                    b.ToTable("DetailVente");
                });

            modelBuilder.Entity("Solution_Magasin.Models.Employe", b =>
                {
                    b.Property<int>("IdUtilisateur")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_utilisateur");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUtilisateur"));

                    b.Property<string>("Cin")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("CIN");

                    b.Property<DateOnly?>("DateEmbauche")
                        .HasColumnType("date")
                        .HasColumnName("dateEmbauche");

                    b.Property<string>("NomEmp")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nom_emp");

                    b.Property<string>("PrenomEmp")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("prenom_emp");

                    b.HasKey("IdUtilisateur")
                        .HasName("PK__Employe__1A4FA5B827B60C55");

                    b.ToTable("Employe");
                });

            modelBuilder.Entity("Solution_Magasin.Models.Facture", b =>
                {
                    b.Property<int>("IdFacture")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_facture");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFacture"));

                    b.Property<string>("CodeFacture")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("code_facture");

                    b.Property<DateOnly?>("DateFacture")
                        .HasColumnType("date")
                        .HasColumnName("date_facture");

                    b.Property<string>("FilePath")
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("file_path");

                    b.Property<int>("IdVente")
                        .HasColumnType("int")
                        .HasColumnName("id_vente");

                    b.Property<double?>("MontantTotal")
                        .HasColumnType("float")
                        .HasColumnName("montant_total");

                    b.HasKey("IdFacture")
                        .HasName("PK__Facture__6C08ED575425E103");

                    b.HasIndex("IdVente");

                    b.ToTable("Facture");
                });

            modelBuilder.Entity("Solution_Magasin.Models.Fournisseur", b =>
                {
                    b.Property<int>("IdFourni")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_fourni");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFourni"));

                    b.Property<string>("AdresseFourni")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("adresse_fourni");

                    b.Property<string>("Cin")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("CIN");

                    b.Property<string>("MailFourni")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("mail_fourni");

                    b.Property<string>("NomFourni")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nom_fourni");

                    b.Property<string>("PrenomFourni")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("prenom_fourni");

                    b.Property<string>("TelFourni")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("tel_fourni");

                    b.HasKey("IdFourni")
                        .HasName("PK__Fourniss__035DEECF4FD13219");

                    b.ToTable("Fournisseur");
                });

            modelBuilder.Entity("Solution_Magasin.Models.NotificationStock", b =>
                {
                    b.Property<int>("IdNot")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_not");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdNot"));

                    b.Property<DateTime?>("DateNot")
                        .HasColumnType("datetime")
                        .HasColumnName("date_not");

                    b.Property<int>("IdArticle")
                        .HasColumnType("int")
                        .HasColumnName("id_article");

                    b.Property<string>("Msg")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("msg");

                    b.Property<bool?>("Vu")
                        .HasColumnType("bit")
                        .HasColumnName("vu");

                    b.HasKey("IdNot")
                        .HasName("PK__Notifica__6E4C7671050D7F42");

                    b.HasIndex("IdArticle");

                    b.ToTable("NotificationStock");
                });

            modelBuilder.Entity("Solution_Magasin.Models.Payment", b =>
                {
                    b.Property<int>("IdPayment")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_payment");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPayment"));

                    b.Property<DateTime?>("DatePayment")
                        .HasColumnType("datetime")
                        .HasColumnName("date_payment");

                    b.Property<bool?>("EstPaye")
                        .HasColumnType("bit")
                        .HasColumnName("estPaye");

                    b.Property<string>("Methode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("methode");

                    b.HasKey("IdPayment")
                        .HasName("PK__Payment__862FEFE014B98D38");

                    b.ToTable("Payment");
                });

            modelBuilder.Entity("Solution_Magasin.Models.Presence", b =>
                {
                    b.Property<int>("IdPr")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_pr");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPr"));

                    b.Property<DateOnly?>("DateP")
                        .HasColumnType("date")
                        .HasColumnName("dateP");

                    b.Property<TimeOnly?>("HeureArrive")
                        .HasColumnType("time")
                        .HasColumnName("heure_arrive");

                    b.Property<TimeOnly?>("HeureDepart")
                        .HasColumnType("time")
                        .HasColumnName("heure_depart");

                    b.Property<int>("IdUtilisateur")
                        .HasColumnType("int")
                        .HasColumnName("id_utilisateur");

                    b.HasKey("IdPr")
                        .HasName("PK__Presence__0148A34E4E909523");

                    b.HasIndex("IdUtilisateur");

                    b.ToTable("Presence");
                });

            modelBuilder.Entity("Solution_Magasin.Models.Retour", b =>
                {
                    b.Property<int>("IdRetour")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_retour");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRetour"));

                    b.Property<DateTime?>("DateRetour")
                        .HasColumnType("datetime")
                        .HasColumnName("date_retour");

                    b.Property<int>("IdArticle")
                        .HasColumnType("int")
                        .HasColumnName("id_article");

                    b.Property<int>("IdVente")
                        .HasColumnType("int")
                        .HasColumnName("id_vente");

                    b.Property<string>("Motif")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("motif");

                    b.HasKey("IdRetour")
                        .HasName("PK__Retour__4E89E94F61945E7A");

                    b.HasIndex("IdArticle");

                    b.HasIndex("IdVente");

                    b.ToTable("Retour");
                });

            modelBuilder.Entity("Solution_Magasin.Models.Review", b =>
                {
                    b.Property<int>("IdReview")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_review");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdReview"));

                    b.Property<string>("Comment")
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("comment");

                    b.Property<int>("IdArticle")
                        .HasColumnType("int")
                        .HasColumnName("id_article");

                    b.Property<int>("IdClient")
                        .HasColumnType("int")
                        .HasColumnName("id_client");

                    b.Property<int?>("Rating")
                        .HasColumnType("int")
                        .HasColumnName("rating");

                    b.HasKey("IdReview")
                        .HasName("PK__Review__2F79F8C7912B0A56");

                    b.HasIndex("IdArticle");

                    b.HasIndex("IdClient");

                    b.ToTable("Review");
                });

            modelBuilder.Entity("Solution_Magasin.Models.Stock", b =>
                {
                    b.Property<int>("IdSt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_st");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSt"));

                    b.Property<DateOnly?>("DateModification")
                        .HasColumnType("date")
                        .HasColumnName("date_modification");

                    b.Property<int>("IdArticle")
                        .HasColumnType("int")
                        .HasColumnName("id_article");

                    b.Property<int?>("QteDispo")
                        .HasColumnType("int")
                        .HasColumnName("qte_dispo");

                    b.Property<int?>("Stockmax")
                        .HasColumnType("int")
                        .HasColumnName("stockmax");

                    b.Property<int?>("Stockmin")
                        .HasColumnType("int")
                        .HasColumnName("stockmin");

                    b.HasKey("IdSt")
                        .HasName("PK__Stock__014858EB29631BEF");

                    b.HasIndex("IdArticle");

                    b.ToTable("Stock");
                });

            modelBuilder.Entity("Solution_Magasin.Models.Vente", b =>
                {
                    b.Property<int>("IdVente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_vente");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdVente"));

                    b.Property<string>("AdresseLiv")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("adresse_liv");

                    b.Property<DateTime?>("DateVente")
                        .HasColumnType("datetime")
                        .HasColumnName("date_vente");

                    b.Property<int>("IdClient")
                        .HasColumnType("int")
                        .HasColumnName("id_client");

                    b.Property<int?>("IdPayment")
                        .HasColumnType("int")
                        .HasColumnName("id_payment");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status");

                    b.Property<double?>("TotalV")
                        .HasColumnType("float")
                        .HasColumnName("total_v");

                    b.HasKey("IdVente")
                        .HasName("PK__Vente__459533B319319C7A");

                    b.HasIndex("IdClient");

                    b.HasIndex("IdPayment");

                    b.ToTable("Vente");
                });

            modelBuilder.Entity("Solution_Magasin.Models.Achat", b =>
                {
                    b.HasOne("Solution_Magasin.Models.Fournisseur", "IdFourniNavigation")
                        .WithMany("Achats")
                        .HasForeignKey("IdFourni")
                        .IsRequired()
                        .HasConstraintName("FK__Achat__id_fourni__4D94879B");

                    b.Navigation("IdFourniNavigation");
                });

            modelBuilder.Entity("Solution_Magasin.Models.Article", b =>
                {
                    b.HasOne("Solution_Magasin.Models.Categorie", "IdCatNavigation")
                        .WithMany("Articles")
                        .HasForeignKey("IdCat")
                        .HasConstraintName("FK__Article__id_cat__44FF419A");

                    b.Navigation("IdCatNavigation");
                });

            modelBuilder.Entity("Solution_Magasin.Models.DetailAchat", b =>
                {
                    b.HasOne("Solution_Magasin.Models.Achat", "IdAchatNavigation")
                        .WithMany("DetailAchats")
                        .HasForeignKey("IdAchat")
                        .IsRequired()
                        .HasConstraintName("FK__DetailAch__id_ac__5070F446");

                    b.HasOne("Solution_Magasin.Models.Article", "IdArticleNavigation")
                        .WithMany("DetailAchats")
                        .HasForeignKey("IdArticle")
                        .IsRequired()
                        .HasConstraintName("FK__DetailAch__id_ar__5165187F");

                    b.Navigation("IdAchatNavigation");

                    b.Navigation("IdArticleNavigation");
                });

            modelBuilder.Entity("Solution_Magasin.Models.DetailVente", b =>
                {
                    b.HasOne("Solution_Magasin.Models.Article", "IdArticleNavigation")
                        .WithMany("DetailVentes")
                        .HasForeignKey("IdArticle")
                        .IsRequired()
                        .HasConstraintName("FK__DetailVen__id_ar__5AEE82B9");

                    b.HasOne("Solution_Magasin.Models.Vente", "IdVenteNavigation")
                        .WithMany("DetailVentes")
                        .HasForeignKey("IdVente")
                        .IsRequired()
                        .HasConstraintName("FK__DetailVen__id_ve__59FA5E80");

                    b.Navigation("IdArticleNavigation");

                    b.Navigation("IdVenteNavigation");
                });

            modelBuilder.Entity("Solution_Magasin.Models.Facture", b =>
                {
                    b.HasOne("Solution_Magasin.Models.Vente", "IdVenteNavigation")
                        .WithMany("Factures")
                        .HasForeignKey("IdVente")
                        .IsRequired()
                        .HasConstraintName("FK__Facture__id_vent__619B8048");

                    b.Navigation("IdVenteNavigation");
                });

            modelBuilder.Entity("Solution_Magasin.Models.NotificationStock", b =>
                {
                    b.HasOne("Solution_Magasin.Models.Article", "IdArticleNavigation")
                        .WithMany("NotificationStocks")
                        .HasForeignKey("IdArticle")
                        .IsRequired()
                        .HasConstraintName("FK__Notificat__id_ar__4AB81AF0");

                    b.Navigation("IdArticleNavigation");
                });

            modelBuilder.Entity("Solution_Magasin.Models.Presence", b =>
                {
                    b.HasOne("Solution_Magasin.Models.Employe", "IdUtilisateurNavigation")
                        .WithMany("Presences")
                        .HasForeignKey("IdUtilisateur")
                        .IsRequired()
                        .HasConstraintName("FK__Presence__id_uti__403A8C7D");

                    b.Navigation("IdUtilisateurNavigation");
                });

            modelBuilder.Entity("Solution_Magasin.Models.Retour", b =>
                {
                    b.HasOne("Solution_Magasin.Models.Article", "IdArticleNavigation")
                        .WithMany("Retours")
                        .HasForeignKey("IdArticle")
                        .IsRequired()
                        .HasConstraintName("FK__Retour__id_artic__6477ECF3");

                    b.HasOne("Solution_Magasin.Models.Vente", "IdVenteNavigation")
                        .WithMany("Retours")
                        .HasForeignKey("IdVente")
                        .IsRequired()
                        .HasConstraintName("FK__Retour__id_vente__656C112C");

                    b.Navigation("IdArticleNavigation");

                    b.Navigation("IdVenteNavigation");
                });

            modelBuilder.Entity("Solution_Magasin.Models.Review", b =>
                {
                    b.HasOne("Solution_Magasin.Models.Article", "IdArticleNavigation")
                        .WithMany("Reviews")
                        .HasForeignKey("IdArticle")
                        .IsRequired()
                        .HasConstraintName("FK__Review__id_artic__5EBF139D");

                    b.HasOne("Solution_Magasin.Models.Client", "IdClientNavigation")
                        .WithMany("Reviews")
                        .HasForeignKey("IdClient")
                        .IsRequired()
                        .HasConstraintName("FK__Review__id_clien__5DCAEF64");

                    b.Navigation("IdArticleNavigation");

                    b.Navigation("IdClientNavigation");
                });

            modelBuilder.Entity("Solution_Magasin.Models.Stock", b =>
                {
                    b.HasOne("Solution_Magasin.Models.Article", "IdArticleNavigation")
                        .WithMany("Stocks")
                        .HasForeignKey("IdArticle")
                        .IsRequired()
                        .HasConstraintName("FK__Stock__id_articl__47DBAE45");

                    b.Navigation("IdArticleNavigation");
                });

            modelBuilder.Entity("Solution_Magasin.Models.Vente", b =>
                {
                    b.HasOne("Solution_Magasin.Models.Client", "IdClientNavigation")
                        .WithMany("Ventes")
                        .HasForeignKey("IdClient")
                        .IsRequired()
                        .HasConstraintName("FK__Vente__id_client__5629CD9C");

                    b.HasOne("Solution_Magasin.Models.Payment", "IdPaymentNavigation")
                        .WithMany("Ventes")
                        .HasForeignKey("IdPayment")
                        .HasConstraintName("FK__Vente__id_paymen__571DF1D5");

                    b.Navigation("IdClientNavigation");

                    b.Navigation("IdPaymentNavigation");
                });

            modelBuilder.Entity("Solution_Magasin.Models.Achat", b =>
                {
                    b.Navigation("DetailAchats");
                });

            modelBuilder.Entity("Solution_Magasin.Models.Article", b =>
                {
                    b.Navigation("DetailAchats");

                    b.Navigation("DetailVentes");

                    b.Navigation("NotificationStocks");

                    b.Navigation("Retours");

                    b.Navigation("Reviews");

                    b.Navigation("Stocks");
                });

            modelBuilder.Entity("Solution_Magasin.Models.Categorie", b =>
                {
                    b.Navigation("Articles");
                });

            modelBuilder.Entity("Solution_Magasin.Models.Client", b =>
                {
                    b.Navigation("Reviews");

                    b.Navigation("Ventes");
                });

            modelBuilder.Entity("Solution_Magasin.Models.Employe", b =>
                {
                    b.Navigation("Presences");
                });

            modelBuilder.Entity("Solution_Magasin.Models.Fournisseur", b =>
                {
                    b.Navigation("Achats");
                });

            modelBuilder.Entity("Solution_Magasin.Models.Payment", b =>
                {
                    b.Navigation("Ventes");
                });

            modelBuilder.Entity("Solution_Magasin.Models.Vente", b =>
                {
                    b.Navigation("DetailVentes");

                    b.Navigation("Factures");

                    b.Navigation("Retours");
                });
#pragma warning restore 612, 618
        }
    }
}
